name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: cshell 
      run: ./cshell testScript.txt
    - name: check files 
      if: always()
      run: ls 
